---
title: Nightlights in economic research
author: R package build
date: '2021-10-15'
slug: []
categories: []
tags: []
description: ~
toc: yes
authors: []
series: []
lastmod: '2021-10-15T17:52:27-04:00'
featuredVideo: ~
featuredImage: ~
---


## Brief history of nightligts in research

Nightlights data is 
Given the resolution and frequency, nightlights have been used to proxy economic activity. It is helpful to however dissect the level 

## Nightlights



## VIIRS vs DMSP why the low coefficients

From 2012, the newer generation of nightlights observations, the Visible Infrared Imaging Radiometer Suite (VIIRS), that replaced DMSP-OLS overcame the limitations discussed above.
However, the ultra-low light detection capability of VIIRS DNB also comes with a drawback. It is contaminated by several light sources not directly related to human activities. These sources include stray lights, moon light, lightning, background “noise”, atmospheric backscatter, and others (Elvidge 


## Scale of regressions

### At National



### At Subnational


## Call: 15-Oct
- Run stringency index charts
- War and crisis should be a low bar
- Cleaning make sense
  - large samples remove noise
  - standarize rather than customize 
  - 
- Imaginging NTL potential as a bar
  - ceiling: to predict economic activity
  - floor: explain war and crises 
  - Remember main idea of data quality improvement
  
- to do
  - covid stringency index by month and country
  - check for wars
  - filter habitable, manufacturing adm2 polygons
    - population
    - built-up lulc
  - afg (later): find aid




