---
title: Trends
author: Parth
date: '2021-10-14'
slug: []
categories: []
tags: []
description: ~
toc: yes
authors: []
series: []
lastmod: '2021-10-14T01:19:03-04:00'
featuredVideo: ~
featuredImage: ~
---



```{r setup, include=FALSE}
knitr::opts_chunk$set(collapse = TRUE)
library(ggplot2); library(data.table);library(fixest)
options(scipen=99)
```

# Distribution and trends
Trends from VIIRS annual product released recently for 2012-2020.

```{r, echo=F, warning=F, message=F}
load('/Users/parthkhare/Desktop/CGD/Projects/Globalsat/data/HWS & country level/country_year regdata/Ctyr_Jul1_BaseregHML.RData')


# Aggregate data to world
br <- data.table(br)
brglb <- br[,.(sum_pix = sum(sum_pix, na.rm=T), pol_area = sum(pol_area, na.rm=T),
                       sum_pix_clb = sum(sum_pix_clb, na.rm=T), 
                       pos_sumpx = sum(pos_sumpx, na.rm=T),
                       imf_rgdp_lcu = sum(imf_rgdp_lcu, na.rm=T), 
                       pwt_rgdpna = sum(pwt_rgdpna, na.rm=T),
                       WDI = sum(WDI, na.rm=T), 
                       ox_anrgdp_lcu = sum(ox_anrgdp_lcu, na.rm=T)),
                    by = .(incat,year)]

# Global trends: GDP
ggplot(brglb, aes(y=log(WDI), x=year, color=incat, group=incat)) + 
  geom_point(size=0.5) + geom_smooth(size=0.5,se=F) + 
  ggtitle('Annual GDP by country groups') + ylab('log WDI') + xlab('years') 

# Global trends: GDP
ggplot(brglb, aes(y=log(sum_pix), x=year, color=incat, group=incat)) + 
  geom_point(size=0.5) + geom_smooth(size=0.5,se=F) + 
  ggtitle('Annual NTL by country groups') + ylab('log VIIRS') + xlab('years') 
```
